name: build-test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
    - uses: actions/upload-artifact@v2
      id: snapcraft
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}
